build:
  tests:
    override:
      - true

  nodes:
    tests: true
    analysis:
      tests:
        override: [php-scrutinizer-run]

checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        relational: false
        concatenation: true
filter:
  excluded_paths:
    - 'tests/*'
    - 'vendor/*'