language: php
sudo: false
dist: trusty
php:
  - 7.2
  - 7.1

script:
  - composer install
  - php vendor/bin/codecept run --coverage --coverage-xml
after_success:
  - bash <(curl -s https://codecov.io/bash)