language: php
sudo: false
dist: trusty
php:
  - 7.3
  - 7.2
  - 7.1
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
script:
  - composer install
  - cp tests/_config/params-example.php tests/_config/params.php
  - php vendor/bin/codecept run --coverage --coverage-xml
after_success:
  - bash <(curl -s https://codecov.io/bash)